[package]
name = "app"
version = "0.1.0"
authors = ["alekspickle <aleks.work2222@gmail.com>"]
edition = "2018"

[dependencies]
clap="2.33.0"
rtracer-rs= {path = "../"}
serde_json="1.0.41"
image = "0.22.3"